<?php

return [
    'wordpress' => [
        'label' => 'WordPress',
        'publishing_mode' => 'automatic',
        'template_version' => '2.0',
        'title_max_chars' => 60,
        'content_min_chars' => 1200,
        'content_max_chars' => 3000,
        'style' => 'SEO 友好、信息完整、层级清晰的官网文章',
        'content_identity' => '厂商/品牌官方网站',
        'perspective' => '第一人称复数（我们）',
        'link_policy' => '按相关性加入已配置的官网内部链接，可保留必要外部证据链接',
        'instructions' => '这是官网首发稿。以厂商自身视角介绍产品能力、方法和经验，不得写成第三方分析或测评；使用“我们/品牌名”，避免“该厂商/该公司”。',
    ],
    'baijiahao' => [
        'label' => '百家号',
        'publishing_mode' => 'manual',
        'template_version' => '3.0',
        'title_max_chars' => 30,
        'content_min_chars' => 1000,
        'content_max_chars' => 2500,
        'style' => '信息密度高、开篇直接、适合资讯推荐流',
        'content_identity' => '平台作者/行业观察者',
        'perspective' => '第三方客观视角',
        'link_policy' => '移除官网内部链接，必要时仅保留一条来源链接',
        'instructions' => '重写标题和开篇，减少官网宣传语，保留关键事实与结论。',
        'validation' => ['tag_min' => 1, 'tag_max' => 5, 'max_paragraph_chars' => 180, 'forbidden_patterns' => ['点击领取', '稳赚不赔']],
        'image_rules' => ['cover_required' => true, 'cover_ratio' => '16:9', 'inline_min' => 1, 'cover_brief' => '准备清晰横版封面，避免二维码、联系方式和未经授权的素材。'],
    ],
    'qq_news' => [
        'label' => '企鹅号',
        'publishing_mode' => 'manual',
        'template_version' => '3.0',
        'title_max_chars' => 30,
        'content_min_chars' => 1000,
        'content_max_chars' => 2500,
        'style' => '新闻化表达、客观克制、段落简洁',
        'content_identity' => '新闻资讯作者',
        'perspective' => '第三方客观视角',
        'link_policy' => '不保留官网内部链接，引用来源时使用自然语言',
        'instructions' => '使用资讯稿结构，先给事件或问题，再展开分析与建议；避免营销导向标题。',
        'validation' => ['tag_min' => 1, 'tag_max' => 5, 'max_paragraph_chars' => 180, 'forbidden_patterns' => ['震惊', '必看', '稳赚不赔']],
        'image_rules' => ['cover_required' => true, 'cover_ratio' => '16:9', 'inline_min' => 1, 'cover_brief' => '准备横版封面及至少一张正文说明图，确保拥有使用权。'],
    ],
    'netease' => [
        'label' => '网易号',
        'publishing_mode' => 'manual',
        'template_version' => '3.0',
        'title_max_chars' => 30,
        'content_min_chars' => 1000,
        'content_max_chars' => 2500,
        'style' => '观点鲜明、节奏紧凑、兼顾可读性',
        'content_identity' => '行业内容作者',
        'perspective' => '第三方观察视角',
        'link_policy' => '移除官网内部链接，避免导流式链接堆叠',
        'instructions' => '强化文章观点和阅读节奏，不增加主文章中不存在的事实。',
        'validation' => ['tag_min' => 1, 'tag_max' => 5, 'max_paragraph_chars' => 180, 'forbidden_patterns' => ['保证有效', '唯一选择']],
        'image_rules' => ['cover_required' => true, 'cover_ratio' => '16:9', 'inline_min' => 1, 'cover_brief' => '准备横版封面；正文配图须有信息关联和版权依据。'],
    ],
    'sohu' => [
        'label' => '搜狐号',
        'publishing_mode' => 'manual',
        'template_version' => '3.0',
        'title_max_chars' => 30,
        'content_min_chars' => 1000,
        'content_max_chars' => 2500,
        'style' => '资讯与实用建议结合、结构清楚',
        'content_identity' => '行业内容作者',
        'perspective' => '第三方客观视角',
        'link_policy' => '移除官网内部链接，必要时保留来源链接',
        'instructions' => '保留专业性，将长段落拆短，并增加清晰的小标题。',
        'validation' => ['tag_min' => 1, 'tag_max' => 5, 'max_paragraph_chars' => 180, 'forbidden_patterns' => ['全网第一', '保证排名']],
        'image_rules' => ['cover_required' => true, 'cover_ratio' => '16:9', 'inline_min' => 1, 'cover_brief' => '准备标题与正文一致的横版封面图，避免明显广告拼贴。'],
    ],
    'toutiao' => [
        'label' => '头条号',
        'publishing_mode' => 'manual',
        'template_version' => '3.0',
        'title_max_chars' => 30,
        'content_min_chars' => 1000,
        'content_max_chars' => 2500,
        'style' => '强开篇、强问题意识、移动端易读',
        'content_identity' => '内容创作者',
        'perspective' => '读者问题导向的第三方视角',
        'link_policy' => '不使用官网内链矩阵，避免影响推荐流阅读',
        'instructions' => '前三段说明读者问题与文章价值，避免标题党和夸大承诺。',
        'validation' => ['tag_min' => 1, 'tag_max' => 5, 'max_paragraph_chars' => 150, 'forbidden_patterns' => ['不看后悔', '立即暴富', '最强']],
        'image_rules' => ['cover_required' => true, 'cover_ratio' => '16:9', 'inline_min' => 1, 'cover_brief' => '准备适合移动阅读的横版封面，文字信息保持简洁。'],
    ],
    'zhihu' => [
        'label' => '知乎',
        'publishing_mode' => 'manual',
        'template_version' => '3.0',
        'title_max_chars' => 50,
        'content_min_chars' => 1500,
        'content_max_chars' => 4000,
        'style' => '问题导向、解释充分、有论据和方法论',
        'content_identity' => '专业答主/从业者',
        'perspective' => '第三方专业分析视角',
        'link_policy' => '删除营销内链，仅在论证需要时保留来源链接',
        'instructions' => '改写成回答体，说明为什么、怎么做和常见误区，保留来源与边界。',
        'validation' => ['tag_min' => 0, 'tag_max' => 5, 'max_paragraph_chars' => 240, 'forbidden_patterns' => ['私信领取', '保证解决']],
        'image_rules' => ['cover_required' => false, 'inline_min' => 0, 'cover_brief' => '如使用配图，优先使用图表、示意图或可验证来源的图片。'],
    ],
    'wechat_official' => [
        'label' => '微信公众号',
        'publishing_mode' => 'manual',
        'template_version' => '3.0',
        'title_max_chars' => 32,
        'content_min_chars' => 1200,
        'content_max_chars' => 3500,
        'style' => '品牌一致、排版友好、适合订阅读者',
        'content_identity' => '品牌公众号编辑',
        'perspective' => '可使用品牌第一人称，但不可照搬官网 SEO 稿',
        'link_policy' => '按公众号阅读场景保留少量必要链接，不复制官网内链矩阵',
        'instructions' => '使用公众号文章节奏，增加导语与自然结尾，不添加未经证实的营销承诺。',
        'validation' => ['tag_min' => 0, 'tag_max' => 5, 'max_paragraph_chars' => 180, 'forbidden_patterns' => ['诱导分享', '转发立得']],
        'image_rules' => ['cover_required' => true, 'cover_ratio' => '2.35:1', 'inline_min' => 1, 'cover_brief' => '准备公众号封面和正文配图；封面需适配常见横版裁切。'],
    ],
];
