<?php

return [
    'wordpress' => [
        'label' => 'WordPress',
        'publishing_mode' => 'automatic',
        'template_version' => '1.0',
        'title_max_chars' => 60,
        'content_min_chars' => 1200,
        'content_max_chars' => 3000,
        'style' => 'SEO 友好、信息完整、层级清晰的官网文章',
        'instructions' => '保留主文章事实、关键词、引用和核心结构，适合官网长期收录与搜索访问。',
    ],
    'baijiahao' => [
        'label' => '百家号',
        'publishing_mode' => 'manual',
        'template_version' => '1.0',
        'title_max_chars' => 30,
        'content_min_chars' => 1000,
        'content_max_chars' => 2500,
        'style' => '信息密度高、开篇直接、适合资讯推荐流',
        'instructions' => '重写标题和开篇，减少官网宣传语，保留关键事实与结论。',
    ],
    'qq_news' => [
        'label' => '腾讯新闻',
        'publishing_mode' => 'manual',
        'template_version' => '1.0',
        'title_max_chars' => 30,
        'content_min_chars' => 1000,
        'content_max_chars' => 2500,
        'style' => '新闻化表达、客观克制、段落简洁',
        'instructions' => '使用新闻稿结构重写，先给事件或问题，再展开分析与建议。',
    ],
    'netease' => [
        'label' => '网易号',
        'publishing_mode' => 'manual',
        'template_version' => '1.0',
        'title_max_chars' => 30,
        'content_min_chars' => 1000,
        'content_max_chars' => 2500,
        'style' => '观点鲜明、节奏紧凑、兼顾可读性',
        'instructions' => '强化文章观点和阅读节奏，不增加主文章中不存在的事实。',
    ],
    'sohu' => [
        'label' => '搜狐号',
        'publishing_mode' => 'manual',
        'template_version' => '1.0',
        'title_max_chars' => 30,
        'content_min_chars' => 1000,
        'content_max_chars' => 2500,
        'style' => '资讯与实用建议结合、结构清楚',
        'instructions' => '保留专业性，将长段落拆短，并增加清晰的小标题。',
    ],
    'toutiao' => [
        'label' => '头条号',
        'publishing_mode' => 'manual',
        'template_version' => '1.0',
        'title_max_chars' => 30,
        'content_min_chars' => 1000,
        'content_max_chars' => 2500,
        'style' => '强开篇、强问题意识、移动端易读',
        'instructions' => '前三段说明读者问题与文章价值，避免标题党和夸大承诺。',
    ],
    'zhihu' => [
        'label' => '知乎',
        'publishing_mode' => 'manual',
        'template_version' => '1.0',
        'title_max_chars' => 50,
        'content_min_chars' => 1500,
        'content_max_chars' => 4000,
        'style' => '问题导向、解释充分、有论据和方法论',
        'instructions' => '改写成回答体，说明为什么、怎么做和常见误区，保留来源与边界。',
    ],
    'wechat_official' => [
        'label' => '微信公众号',
        'publishing_mode' => 'manual',
        'template_version' => '1.0',
        'title_max_chars' => 32,
        'content_min_chars' => 1200,
        'content_max_chars' => 3500,
        'style' => '品牌一致、排版友好、适合订阅读者',
        'instructions' => '使用公众号文章节奏，增加导语与自然结尾，不添加未经证实的营销承诺。',
    ],
];
