@extends('admin.layouts.app')

@section('content')
    @php($pack = $variant->publication_payload ?? [])
    <div class="mx-auto max-w-5xl px-4 sm:px-0">
        <div class="mb-8 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div><a href="{{ route('admin.content-groups.show', $contentGroup) }}" class="text-sm font-semibold text-gray-500 hover:text-gray-700">← 返回发布包</a><h1 class="mt-3 text-2xl font-bold text-gray-900">{{ $platform['label'] ?? $variant->platform }} 发布预览</h1><p class="mt-2 text-sm text-gray-600">V{{ $variant->version }} · 规则版本 {{ $variant->platform_specification_version ?? $variant->template_version }}。请在发布前按账号后台的实时提示完成最终检查。</p></div>
            <button type="button" data-copy="full" class="rounded-md bg-violet-600 px-4 py-2 text-sm font-semibold text-white hover:bg-violet-700">一键复制发布稿</button>
        </div>
        <div class="grid grid-cols-1 gap-6 lg:grid-cols-3">
            <main class="space-y-5 lg:col-span-2">
                <section class="rounded-xl border border-gray-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-xs font-semibold uppercase tracking-wide text-gray-500">标题</h2><button type="button" data-copy="title" class="text-xs font-semibold text-violet-700">复制</button></div><p id="copy-title" class="mt-3 text-xl font-bold text-gray-900">{{ $variant->title }}</p></section>
                <section class="rounded-xl border border-gray-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-xs font-semibold uppercase tracking-wide text-gray-500">摘要</h2><button type="button" data-copy="summary" class="text-xs font-semibold text-violet-700">复制</button></div><p id="copy-summary" class="mt-3 whitespace-pre-wrap text-sm leading-7 text-gray-700">{{ $variant->excerpt }}</p></section>
                <section class="rounded-xl border border-gray-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><h2 class="text-xs font-semibold uppercase tracking-wide text-gray-500">正文</h2><button type="button" data-copy="content" class="text-xs font-semibold text-violet-700">复制</button></div><article id="copy-content" class="mt-4 whitespace-pre-wrap text-sm leading-8 text-gray-800">{{ $variant->content }}</article></section>
            </main>
            <aside class="space-y-5">
                <section class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">发布就绪检查</h2><div class="mt-3 rounded-md px-3 py-2 text-sm {{ ($variant->publication_readiness['passed'] ?? false) ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700' }}">{{ ($variant->publication_readiness['passed'] ?? false) ? '内容校验通过' : '仍有需要处理的阻断项' }}</div>@foreach (($variant->publication_readiness['blockers'] ?? []) as $item)<p class="mt-2 text-xs text-red-700">• {{ $item }}</p>@endforeach>@foreach (($variant->publication_readiness['warnings'] ?? []) as $item)<p class="mt-2 text-xs text-amber-700">• {{ $item }}</p>@endforeach></section>
                <section class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">素材清单</h2><p class="mt-3 text-sm text-gray-700">封面：{{ ($pack['cover']['required'] ?? false) ? '需要准备' : '可选' }}</p><p class="mt-1 text-xs leading-5 text-gray-500">{{ $pack['cover']['brief'] ?? '请准备与主题一致、已获授权的图片。' }}</p><p class="mt-3 text-sm text-gray-700">正文配图建议：{{ $pack['inline_images']['minimum'] ?? 0 }} 张起</p>@foreach (($pack['inline_images']['briefs'] ?? []) as $brief)<p class="mt-2 text-xs text-gray-600">• {{ $brief }}</p>@endforeach</section>
                <section class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-gray-900">标签</h2><div class="mt-3 flex flex-wrap gap-2">@forelse($variant->tags ?? [] as $tag)<span class="rounded-full bg-violet-50 px-2.5 py-1 text-xs text-violet-700">{{ $tag }}</span>@empty<span class="text-sm text-gray-500">暂无标签</span>@endforelse</div></section>
            </aside>
        </div>
        <section class="mt-6 rounded-xl border border-gray-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold text-gray-900">发布后反馈</h2><p class="mt-1 text-sm text-gray-600">记录人工修改或平台退回原因，方便后续维护规则；不会自动更改已发布内容。</p><form method="POST" action="{{ route('admin.content-groups.variants.feedback', [$contentGroup, $variant]) }}" class="mt-5 grid grid-cols-1 gap-4 md:grid-cols-2">@csrf<label class="text-sm font-semibold text-gray-700">结果<select name="outcome" class="mt-2 block w-full rounded-md border-gray-300 text-sm"><option value="published">已发布</option><option value="manual_adjusted">人工调整后发布</option><option value="rejected">平台退回/未通过</option></select></label><label class="text-sm font-semibold text-gray-700">退回原因或调整项（逗号分隔）<input name="reasons" class="mt-2 block w-full rounded-md border-gray-300 text-sm" placeholder="例如：标题不符合账号后台提示"></label><label class="md:col-span-2 text-sm font-semibold text-gray-700">备注<textarea name="notes" rows="3" class="mt-2 block w-full rounded-md border-gray-300 text-sm"></textarea></label><div class="md:col-span-2"><button class="rounded-md border border-violet-300 bg-white px-4 py-2 text-sm font-semibold text-violet-700 hover:bg-violet-50">记录反馈</button></div></form></section>
    </div>
    <script>
        (() => { const get = (id) => document.getElementById('copy-' + id)?.innerText || ''; const full = () => [get('title'), get('summary'), get('content')].filter(Boolean).join('\n\n'); document.querySelectorAll('[data-copy]').forEach((button) => button.addEventListener('click', async () => { try { await navigator.clipboard.writeText(button.dataset.copy === 'full' ? full() : get(button.dataset.copy)); const before = button.textContent; button.textContent = '已复制'; setTimeout(() => button.textContent = before, 1600); } catch (_) { window.alert('复制失败，请手动选择内容复制。'); } })); })();
    </script>
@endsection
