@extends('admin.layouts.app')

@section('content')
    <div class="mx-auto flex max-w-5xl flex-col gap-6 px-4 sm:px-0">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('admin.writing-rules.index') }}" class="text-sm font-semibold text-blue-600 hover:text-blue-800">← 返回写作规则</a><h1 class="mt-3 text-2xl font-bold text-gray-900">{{ $rule->name }}</h1><p class="mt-1 text-sm text-gray-600">{{ $rule->description ?: '暂无说明' }}</p></div><a href="{{ route('admin.writing-rules.edit', $rule) }}" class="rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700">编辑并创建新版本</a></div>
        @php($settings = $rule->currentVersionRecord()?->settings ?? [])
        <section class="rounded-lg border border-gray-200 bg-white p-6 shadow-sm"><div class="flex flex-wrap items-center gap-3"><span class="rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-700">当前 v{{ $rule->current_version }}</span><span class="rounded-full px-3 py-1 text-sm font-semibold {{ $rule->is_active ? 'bg-emerald-100 text-emerald-700' : 'bg-gray-100 text-gray-600' }}">{{ $rule->is_active ? '启用' : '停用' }}</span><span class="text-sm text-gray-500">{{ $rule->articleType?->name ?: '未分类' }}</span></div><dl class="mt-6 grid grid-cols-1 gap-5 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-gray-500">语言 / 地区</dt><dd class="mt-1 font-semibold text-gray-900">{{ $settings['language'] ?? '—' }} / {{ $settings['country'] ?? '—' }}</dd></div><div><dt class="text-gray-500">语气</dt><dd class="mt-1 font-semibold text-gray-900">{{ $settings['tone'] ?? '—' }}</dd></div><div><dt class="text-gray-500">篇幅</dt><dd class="mt-1 font-semibold text-gray-900">{{ $settings['min_words'] ?? '—' }} - {{ $settings['max_words'] ?? '—' }} 字</dd></div><div><dt class="text-gray-500">小标题</dt><dd class="mt-1 font-semibold text-gray-900">{{ $settings['min_headings'] ?? '—' }} - {{ $settings['max_headings'] ?? '—' }} 个</dd></div></dl></section>
        <section class="rounded-lg border border-gray-200 bg-white shadow-sm"><div class="border-b border-gray-200 px-6 py-4"><h2 class="text-lg font-semibold text-gray-900">版本历史</h2><p class="mt-1 text-xs text-gray-500">历史版本保持不变，已创建项目会继续使用创建时保存的快照。</p></div><div class="divide-y divide-gray-100">@foreach ($rule->versions->sortByDesc('version') as $version)<article class="px-6 py-4"><div class="flex flex-wrap items-center justify-between gap-3"><div><span class="font-semibold text-gray-900">v{{ $version->version }}</span><span class="ml-2 text-sm text-gray-500">{{ $version->change_note ?: ($version->version === 1 ? '初始版本' : '规则更新') }}</span></div><div class="text-xs text-gray-500">{{ $version->createdBy?->display_name ?: $version->createdBy?->username ?: '系统' }} · {{ $version->created_at?->format('Y-m-d H:i') }}</div></div><details class="mt-3"><summary class="cursor-pointer text-xs font-semibold text-blue-600">查看结构化快照</summary><pre class="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-xs leading-5 text-slate-100">{{ json_encode($version->settings, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) }}</pre></details></article>@endforeach</div></section>
    </div>
@endsection
