@extends('admin.layouts.app')

@section('content')
    <div class="mx-auto max-w-4xl px-4 sm:px-0"><a href="{{ $topic ? route('admin.content-topics.show', $topic) : route('admin.content-topics.index') }}" class="text-sm font-semibold text-teal-700">← 返回内容专题</a><h1 class="mt-3 text-2xl font-bold text-gray-900">{{ $topic ? '编辑内容专题' : '新建内容专题' }}</h1><p class="mt-2 text-sm text-gray-600">这些设置将在新建文章时复制为快照，不会改动已创建工作单。</p>
        <form method="POST" action="{{ $topic ? route('admin.content-topics.update', $topic) : route('admin.content-topics.store') }}" class="mt-6 space-y-6 rounded-xl border border-gray-200 bg-white p-6 shadow-sm">@csrf @if($topic) @method('PUT') @endif
            <div class="grid grid-cols-1 gap-5 sm:grid-cols-2"><label class="flex flex-col gap-2 sm:col-span-2"><span class="text-sm font-semibold text-gray-700">专题名称 <span class="text-red-500">*</span></span><input name="name" required maxlength="255" value="{{ old('name', $topic?->name) }}" class="rounded-md border-gray-300 text-sm" placeholder="例如：企业视频会议内容专题"></label><label class="flex flex-col gap-2"><span class="text-sm font-semibold text-gray-700">目标网站</span><input name="website" maxlength="500" value="{{ old('website', $topic?->website) }}" class="rounded-md border-gray-300 text-sm" placeholder="https://example.com"></label><label class="flex flex-col gap-2"><span class="text-sm font-semibold text-gray-700">受众</span><input name="audience" maxlength="500" value="{{ old('audience', $topic?->audience) }}" class="rounded-md border-gray-300 text-sm" placeholder="例如：中小企业 IT 管理者"></label><label class="flex flex-col gap-2"><span class="text-sm font-semibold text-gray-700">默认栏目</span><select name="category_id" class="rounded-md border-gray-300 text-sm"><option value="">新建文章时自行选择</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('category_id', $topic?->category_id) === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></label><label class="flex flex-col gap-2"><span class="text-sm font-semibold text-gray-700">默认写作规则</span><select name="writing_rule_id" class="rounded-md border-gray-300 text-sm"><option value="">新建文章时自行选择</option>@foreach($writingRules as $rule)<option value="{{ $rule->id }}" @selected((string) old('writing_rule_id', $topic?->writing_rule_id) === (string) $rule->id)>{{ $rule->name }} · v{{ $rule->current_version }}</option>@endforeach</select></label></div>
            <label class="flex flex-col gap-2"><span class="text-sm font-semibold text-gray-700">知识库范围</span><select name="knowledge_base_ids[]" multiple class="min-h-28 rounded-md border-gray-300 text-sm">@foreach($knowledgeBases as $knowledgeBase)<option value="{{ $knowledgeBase->id }}" @selected(in_array($knowledgeBase->id, old('knowledge_base_ids', $topic?->knowledge_base_ids ?? [])))>{{ $knowledgeBase->name }}</option>@endforeach</select></label>
            <div class="grid grid-cols-1 gap-5 sm:grid-cols-2"><label class="flex flex-col gap-2"><span class="text-sm font-semibold text-gray-700">URL 资料（每行一个）</span><textarea name="reference_urls" rows="5" class="rounded-md border-gray-300 text-sm">{{ old('reference_urls', implode("\n", $topic?->reference_urls ?? [])) }}</textarea></label><label class="flex flex-col gap-2"><span class="text-sm font-semibold text-gray-700">主题集群 / 关键词（每行一个）</span><textarea name="keyword_clusters" rows="5" class="rounded-md border-gray-300 text-sm">{{ old('keyword_clusters', implode("\n", $topic?->keyword_clusters ?? [])) }}</textarea></label></div>
            <label class="flex flex-col gap-2"><span class="text-sm font-semibold text-gray-700">素材范围</span><textarea name="material_scope" rows="3" class="rounded-md border-gray-300 text-sm">{{ old('material_scope', $topic?->material_scope) }}</textarea></label><div class="grid grid-cols-1 gap-5 sm:grid-cols-2"><label class="flex flex-col gap-2"><span class="text-sm font-semibold text-gray-700">内容目标</span><textarea name="content_goal" rows="3" class="rounded-md border-gray-300 text-sm">{{ old('content_goal', $topic?->content_goal) }}</textarea></label><label class="flex flex-col gap-2"><span class="text-sm font-semibold text-gray-700">发布节奏</span><input name="publishing_cadence" maxlength="255" value="{{ old('publishing_cadence', $topic?->publishing_cadence) }}" class="rounded-md border-gray-300 text-sm" placeholder="例如：每周 2 篇"></label></div>
            <label class="flex items-center gap-2 text-sm text-gray-700"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $topic?->is_active ?? true)) class="rounded border-gray-300 text-teal-600">启用专题</label><div class="flex justify-end gap-3 border-t border-gray-100 pt-5"><a href="{{ route('admin.content-topics.index') }}" class="rounded-md border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">取消</a><button class="rounded-md bg-teal-600 px-4 py-2 text-sm font-semibold text-white">保存专题</button></div>
        </form></div>
@endsection
