@extends('admin.layouts.app')

@section('content')
    <div class="mx-auto flex max-w-6xl flex-col gap-6 px-4 sm:px-0">
        <section class="rounded-2xl border border-teal-100 bg-gradient-to-br from-teal-50 via-white to-blue-50 p-6 shadow-sm sm:p-8">
            <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-teal-700">内容专题与选题池</p><h1 class="mt-2 text-2xl font-bold text-gray-900">为连续内容生产建立专题</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-gray-600">专题用于一组有关联的文章，沉淀受众、资料、规则与选题。单篇临时文章仍可直接创建，无需归入专题。</p></div><div class="flex gap-2"><a href="{{ route('admin.content-productions.create') }}" class="rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50">新建单篇文章</a><a href="{{ route('admin.content-topics.create') }}" class="rounded-md bg-teal-600 px-4 py-2 text-sm font-semibold text-white hover:bg-teal-700">新建内容专题</a></div></div>
        </section>
        <section class="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">内容专题</th><th class="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">选题池</th><th class="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wide text-gray-500">文章工作单</th><th class="px-6 py-3 text-right text-xs font-semibold uppercase tracking-wide text-gray-500">操作</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($topics as $topic)<tr class="hover:bg-gray-50"><td class="px-6 py-4"><div class="font-semibold text-gray-900">{{ $topic->name }}</div><div class="mt-1 text-xs text-gray-500">{{ $topic->website ?: '未设置目标网站' }} · {{ $topic->audience ?: '未设置受众' }}</div></td><td class="px-6 py-4 text-sm text-gray-600">{{ $topic->ideas_count }} 个</td><td class="px-6 py-4 text-sm text-gray-600">{{ $topic->productions_count }} 篇</td><td class="px-6 py-4 text-right"><a href="{{ route('admin.content-topics.show', $topic) }}" class="text-sm font-semibold text-teal-700 hover:text-teal-900">查看专题</a></td></tr>@empty<tr><td colspan="4" class="px-6 py-14 text-center text-sm text-gray-500">还没有内容专题。只有连续生产一组相关内容时，才需要建立专题。</td></tr>@endforelse</tbody></table>@if($topics->hasPages())<div class="border-t border-gray-200 px-6 py-4">{{ $topics->links() }}</div>@endif</section>
    </div>
@endsection
